spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/hoshop
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

  servlet:
    multipart:
      max-file-size: 20MB #파일 한 개당 최대 사이즈
      max-request-size: 100MB   #요청 당 최대 파일 크기

itemImgLocation: '/Users/hojun/study/hoshop/item' #상품 이미지 업로드 경로
uploadPath: file:///Users/hojun/study/hoshop/ #리소스 경로

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

